---
name: Linting

on:
    pull_request:
        paths:
        - go/**

jobs:

    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Go 1.23.5
              uses: actions/setup-go@v5
              with:
                go-version: 1.23.5

            # Install golangci-lint
            - name: Install golangci-lint
              run: |
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

            - uses: actions/setup-python@v3
            - uses: pre-commit/action@v3.0.1
