name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: release-${{ github.ref_name }}



  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          tags: cgundlach13/voer:${{ github.ref_name }}
          target: prod
          push: true

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: create_release
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        # build and publish in parallel
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go 1.23.5
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.5

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Install protoc-gen-go-grpc
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Generate protobuf files
      run: make build-proto

    - name: Codegen templ
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin

        go install github.com/a-h/templ/cmd/templ@latest

        templ generate

    - name: Install dependencies
      run: go mod download

    - uses: wangyoucao577/go-release-action@v1
      with:
        release_name: release-${{ github.ref_name }}
        asset_name: voer-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.23.5.linux-amd64.tar.gz"
        project_path: "./cmd/voer"
        binary_name: "voer"
        extra_files: LICENSE README.md
